services:
  php:
    build:
      context: ./.docker/8.3
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - bot-app
networks:
  bot-app:
    driver: bridge
